# Generated by Django 3.1.7 on 2021-02-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_time',
            new_name='date_posted',
        ),
    ]
